apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-hydra
  template:
    metadata:
      labels:
        app: ory-hydra
    spec:
      volumes:
        - name: hydra-config
          configMap:
            name: hydra-config
      containers:
        - name: ory-hydra
          image: oryd/hydra:v26.2
          args: ["serve", "all", "--config", "/etc/config/hydra.yml"]
          volumeMounts:
            - name: hydra-config
              mountPath: /etc/config
              readOnly: true
          ports:
            - name: http
              containerPort: 4444
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"