apiVersion: batch/v1
kind: Job
metadata:
  name: keto-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keto-migrate
          image: oryd/keto:v26.2
          args: ["migrate", "up", "--yes", "--config", "/etc/config/keto.yml"]
          volumeMounts:
            - name: keto-config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: keto-config
          configMap:
            name: keto-config