apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - headlamp/_flux-kustomization.yaml
  - networking/_flux-kustomization.yaml
  - oidc/_flux-kustomization.yaml
  - permissions/_flux-kustomization.yaml
  - postgres/_flux-kustomization.yaml
  - seaweedfs/_flux-kustomization.yaml
  - sources/_flux-kustomization.yaml
  - stalwart/_flux-kustomization.yaml