apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
spec:
  master:
    replicas: 1

  volume:
    replicas: 1
    claims:
      - name: data
        request: 5Gi

  filer:
    replicas: 1

  s3:
    replicas: 1