apiVersion: stalwart.toando.de/v1alpha1
kind: JMAPObject
metadata:
  name: accounts-mail-account
spec:
  clusterRef:
    name: stalwart
  type: Account
  data:
    "@type": User
    name: noreply
    roles: 
      "@type": User
    permissions:
      "@type": Inherit
    encryptionAtRest:
      "@type": Disabled