apiVersion: stalwart.toando.de/v1alpha1
kind: JMAPObject
metadata:
  name: accounts-mail-domain
spec:
  clusterRef:
    name: stalwart
  type: Domain
  data:
    name: accounts.toando.de
    subAdressing:
      "@type": Enabled
    certificateManagement:
      "@type": Manual
    dkimManagement: 
      "@type": Automatic
    dnsManagement":
      "@type": Manual