apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
spec:
  gatewayClassName: traefik

  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.toando.de"

      tls:
        mode: Terminate
        certificateRefs:
          - name: toando-de-tls

      allowedRoutes:
        namespaces:
          from: All