apiVersion: batch/v1
kind: Job
metadata:
  name: kratos-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kratos-migrate
          image: oryd/kratos:v26.2
          args: ["migrate", "sql", "-e", "--yes", "--config", "/etc/config/kratos.yml"]

          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos-secrets
                  key: dsn

          volumeMounts:
            - name: kratos-config
              mountPath: /etc/config
              readOnly: true

      volumes:
        - name: kratos-config
          configMap:
            name: kratos-config