apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-db-credentials
spec:
  target:
    name: mail-db-credentials
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "mail"
      data:
        password: "{{ .password }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mail-db-password