apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      hostNetwork: true
      envoyService:
        type: ClusterIP