apiVersion: stalwart.toando.de/v1alpha1
kind: Cluster
metadata:
  name: stalwart
spec:
  configMapKeyRef:
    name: stalwart-config
    key: config.json
  env:
    name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mail-db-credentials
        key: password