apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: books
  namespace: flux-system
spec:
  interval: 10m
  path: ./products/books
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system