apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hosting-db-credentials
spec:
  target:
    name: hosting-db-credentials
    template:
      metadata:
        annotations:
          cnpg.io/reload: "true"
          replicator.v1.mittwald.de/replicate-to: "hosting"
      type: kubernetes.io/basic-auth
      data:
        username: hosting
        password: "{{ .password }}"

        DATABASE_URL: "postgres://hosting:{{ .password }}@postgres-rw.postgres:5432/hosting?sslmode=disable"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: hosting-db-password