apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: permissions-db-credentials
spec:
  target:
    name: permissions-db-credentials
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "permissions"
      type: kubernetes.io/basic-auth
      data:
        username: permissions
        password: "{{ .password }}"

        DSN: "postgres://permissions:{{ .password }}@postgres-rw.postgres:5432/permissions?sslmode=disable"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: permissions-db-password