apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: identity-database-role
spec:
  cluster:
    name: postgres
  name: identity
  login: true
  passwordSecret:
    name: identity-db-credentials