apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-db-credentials
spec:
  target:
    name: identity-db-credentials
    template:
      metadata:
        annotations:
          cnpg.io/reload: "true"
          replicator.v1.mittwald.de/replicate-to: "identity"
      type: kubernetes.io/basic-auth
      data:
        username: identity
        password: "{{ .password }}"

        DSN: "postgres://identity:{{ .password }}@postgres-rw.postgres:5432/identity?sslmode=disable"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: identity-db-password