apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: keto-config
    files: ["config/keto.yaml"]
  - name: keto-namespaces
    files: ["namespaces"]