apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: accounts-database-role
spec:
  cluster:
    name: postgres
  name: accounts
  login: true
  passwordSecret:
    name: accounts-db-credentials