apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: accounts-db-credentials
spec:
  target:
    name: accounts-db-credentials
    template:
      metadata:
        annotations:
          cnpg.io/reload: "true"
          replicator.v1.mittwald.de/replicate-to: "accounts"
      type: kubernetes.io/basic-auth
      data:
        username: accounts
        password: "{{ .password }}"

        DSN: "postgres://accounts:{{ .password }}@postgres-rw.postgres:5432/accounts?sslmode=disable"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: accounts-db-password