apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migration.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: kratos-config
    files: ["config/kratos.yaml", "config/identity.schema.json"]