apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-db-credentials
spec:
  target:
    name: oidc-db-credentials
    template:
      metadata:
        annotations:
          cnpg.io/reload: "true"
          replicator.v1.mittwald.de/replicate-to: "oidc"
      type: kubernetes.io/basic-auth
      data:
        username: oidc
        password: "{{ .password }}"

        DSN: "postgres://oidc:{{ .password }}@postgres-rw.postgres:5432/oidc?sslmode=disable"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: oidc-db-password