apiVersion: stalwart.toando.de/v1alpha1
kind: Cluster
metadata:
  name: stalwart
spec:
  instances: 1
  dataStore:
    type: PostgreSql
    postgresql:
      host: postgres.postgres
      database: stalwart
      authUsername: stalwart
      authSecret: stalwart_password