apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/_flux-kustomization.yaml
  - cloudnative-pg/_flux-kustomization.yaml
  - external-secrets/_flux-kustomization.yaml
  - kubernetes-replicator/_flux-kustomization.yaml
  - seaweedfs-operator/_flux-kustomization.yaml
  - stalwart-operator/_flux-kustomization.yaml