apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cilium
  targetNamespace: kube-system
  install:
    skipCRDs: false
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml