apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Toandos/platform.git
        revision: main
        directories:
          - path: k8s/**/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/Toandos/platform.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true