apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mail
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/capabilities/mail
  prune: true
  wait: true
  dependsOn:
    - name: stalwart-operator
  sourceRef:
    kind: GitRepository
    name: flux-system