apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18.4

          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: LRkr4DAtqjYOuk01N7g5TlYQYYEQA2Lb

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres
        - name: postgres-init
          configMap:
            name: postgres-init