apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: postgres-init
    files: ["init/01-users.sql", "init/02-databases.sql"]