apiVersion: v1
kind: Secret
metadata:
  name: accounts-ui-ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoieFhqb2phWHgiLCJwYXNzd29yZCI6ImdocF9KZ24ya2pXSmFpQ1NTZGJCRkhmWGpCUkZacmFtSnY0WE9uSVEiLCJhdXRoIjoiZUZocWIycGhXSGc2WjJod1gwcG5iakpyYWxkS1lXbERVMU5rWWtKR1NHWllha0pTUmxweVlXMUtkalJZVDI1SlVRPT0ifX19
