apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-keto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-keto
  template:
    metadata:
      labels:
        app: ory-keto
    spec:
      volumes:
        - name: keto-config
          configMap:
            name: keto-config
        - name: keto-namespaces
          configMap:
            name: keto-namespaces
      containers:
        - name: ory-keto
          image: oryd/keto:v26.2
          args: ["serve", "--config", "/etc/config/keto.yml"]
          volumeMounts:
            - name: keto-config
              mountPath: /etc/config
              readOnly: true
            - name: keto-namespaces
              mountPath: /etc/namespaces
              readOnly: true
          ports:
            - name: read
              containerPort: 4466
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"