apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - helm-release.yaml
  - httproute.yaml
  - database-role.yaml
  - database.yaml
  - db-credentials.yaml

configMapGenerator:
  - name: kratos-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true