apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shared

commonAnnotations:
  replicator.v1.mittwald.de/replicate-to-matching: "toando.de/product"

resources:
  - namespace.yaml
  - github-app-secret.yaml
  - service-account.yaml