providers:
    kubernetesGateway:
        enabled: true

certificatesResolvers:
    le:
        acme:
            email: admin@toando.de
            storage: /etc/letsencrypt/acme.json
            dnsChallenge:
                provider: cloudflare